# Generated by Django 5.0 on 2024-01-20 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("58b1f6b1-64b5-457b-b589-014381480ede"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Branch Name")),
                ("location", models.CharField(max_length=255, verbose_name="Location")),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("58b1f6b1-64b5-457b-b589-014381480ede"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("58b1f6b1-64b5-457b-b589-014381480ede"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="Course Name"),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("duration", models.DurationField(verbose_name="Duration")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="branches.branch",
                        verbose_name="Branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.CreateModel(
            name="CourseSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("58b1f6b1-64b5-457b-b589-014381480ede"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("day_of_week", models.IntegerField(verbose_name="Day of Week")),
                ("active_slots", models.IntegerField(verbose_name="Active Slots")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="branches.course",
                        verbose_name="Course",
                    ),
                ),
                (
                    "week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_schedules",
                        to="core.week",
                        verbose_name="Week",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Schedule",
                "verbose_name_plural": "Course Schedules",
            },
        ),
        migrations.CreateModel(
            name="StudentCourseAgenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("58b1f6b1-64b5-457b-b589-014381480ede"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("day_of_week", models.IntegerField(verbose_name="Day of Week")),
                ("course_date", models.DateField(verbose_name="Course Date")),
                (
                    "course_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_agendas",
                        to="branches.courseschedule",
                        verbose_name="Course Schedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Course Agenda",
                "verbose_name_plural": "Student Course Agendas",
            },
        ),
    ]
