# Generated by Django 5.0 on 2024-01-20 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcourseagenda",
            name="user",
        ),
        migrations.RemoveField(
            model_name="studentenrollment",
            name="user",
        ),
    ]
