# Generated by Django 5.0 on 2024-01-20 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0003_remove_studentcourseagenda_user_and_more"),
        ("users", "0002_remove_teacher_teacher_name_alter_teacher_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourseagenda",
            name="student",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_course_agendas",
                to="users.student",
                verbose_name="User",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_enrollments",
                to="users.student",
                verbose_name="User",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="branch",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c8c632a9-49b7-4c10-bd47-fb30e65837d8"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c8c632a9-49b7-4c10-bd47-fb30e65837d8"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="courseschedule",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c8c632a9-49b7-4c10-bd47-fb30e65837d8"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="studentcourseagenda",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c8c632a9-49b7-4c10-bd47-fb30e65837d8"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="course_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_schedule_enrollments",
                to="branches.courseschedule",
                verbose_name="Course Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c8c632a9-49b7-4c10-bd47-fb30e65837d8"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
    ]
