# Generated by Django 5.0 on 2024-01-20 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0004_studentcourseagenda_student_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="courseschedule",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="studentcourseagenda",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
    ]
