# Generated by Django 5.0 on 2024-01-20 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0005_alter_branch_id_alter_course_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="courseschedule",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="studentcourseagenda",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
    ]
