# Generated by Django 5.0 on 2024-01-20 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0006_alter_branch_id_alter_course_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="duration",
        ),
    ]
