# Generated by Django 5.0 on 2024-01-20 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0007_remove_course_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseschedule",
            name="branch",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_schedules",
                to="branches.branch",
                verbose_name="Branch",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("branch", "course_name", "start_time")},
        ),
    ]
