# Generated by Django 5.0 on 2024-01-20 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0008_courseschedule_branch_alter_course_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["branch__name", "start_time", "course_name"],
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
            },
        ),
    ]
