# Generated by Django 5.0 on 2024-01-20 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0009_alter_course_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseschedule",
            name="branch",
        ),
    ]
