# Generated by Django 5.0 on 2024-01-20 21:54

import django.db.models.deletion
import model_clone.mixin
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0010_remove_courseschedule_branch"),
        ("users", "0009_alter_studentdefaultschedule_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseschedule",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                verbose_name="Day of Week",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="course_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_course_schedule_enrollments",
                to="branches.courseschedule",
                verbose_name="Course Schedule",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_enrollments",
                to="users.student",
                verbose_name="Student",
            ),
        ),
        migrations.CreateModel(
            name="TeacherEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "course_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_course_schedule_enrollments",
                        to="branches.courseschedule",
                        verbose_name="Course Schedule",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_enrollments",
                        to="users.teacher",
                        verbose_name="Teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Enrollment",
                "verbose_name_plural": "Teacher Enrollments",
            },
            bases=(model_clone.mixin.CloneMixin, models.Model),
        ),
        migrations.DeleteModel(
            name="StudentCourseAgenda",
        ),
    ]
