# Generated by Django 5.0 on 2024-01-20 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_teacher_teacher_name_alter_teacher_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="studentdefaultschedule",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="teacherdefaultschedule",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
    ]
