# Generated by Django 5.0 on 2024-01-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_student_id_alter_studentdefaultschedule_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacherdefaultschedule",
            name="default_day",
        ),
        migrations.RemoveField(
            model_name="teacherdefaultschedule",
            name="default_time",
        ),
        migrations.AddField(
            model_name="teacherdefaultschedule",
            name="day",
            field=models.IntegerField(default="1", verbose_name="Day"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacherdefaultschedule",
            name="time",
            field=models.TimeField(default="08:00", verbose_name="Time"),
            preserve_default=False,
        ),
    ]
