# Generated by Django 5.0 on 2024-01-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_teacherdefaultschedule_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentdefaultschedule",
            name="preferred_time",
        ),
        migrations.AlterField(
            model_name="studentdefaultschedule",
            name="preferred_day",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                verbose_name="Preferred Day",
            ),
        ),
    ]
