# Generated by Django 5.0 on 2024-01-20 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_studentdefaultschedule_preferred_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdefaultschedule",
            old_name="preferred_day",
            new_name="day",
        ),
    ]
