# Generated by Django 5.0 on 2024-01-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_preferred_day_studentdefaultschedule_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentdefaultschedule",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_default_schedules",
                to="users.student",
                verbose_name="User",
            ),
        ),
    ]
