# Generated by Django 5.0 on 2024-01-20 18:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.UUID("58b1f6b1-64b5-457b-b589-014381480ede"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("year", models.IntegerField(verbose_name="Year")),
                ("week_number", models.IntegerField(verbose_name="Week Number")),
            ],
            options={
                "verbose_name": "Week",
                "verbose_name_plural": "Weeks",
                "unique_together": {("year", "week_number")},
            },
        ),
    ]
