# Generated by Django 5.0 on 2024-01-20 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("c8c632a9-49b7-4c10-bd47-fb30e65837d8"),
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="Id",
            ),
        ),
    ]
