# Generated by Django 5.0 on 2024-01-20 18:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_week_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("2a7f64be-d1fb-4971-97bc-4398da0041cf"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
    ]
