# Generated by Django 5.0 on 2024-01-20 18:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_week_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="Id",
            ),
        ),
    ]
